joint_a1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a1

joint_a2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a2
    
joint_a3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a3

joint_a4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a4

joint_a5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a5
    
joint_a6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_a6
