joint_a1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a1
    pid: {p: 500.0, i: 5.0, d: 180.0}

joint_a2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a2
    pid: {p: 500.0, i: 5.0, d: 180.0}
    
joint_a3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a3
    pid: {p: 500.0, i: 5.0, d: 180.0}

joint_a4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a4
    pid: {p: 500.0, i: 5.0, d: 180.0}

joint_a5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a5
    pid: {p: 500.0, i: 5.0, d: 180.0}
    
joint_a6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a6
    pid: {p: 500.0, i: 5.0, d: 180.0}
